// Login
export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED_INVALID_CREDS = 'LOGIN_FAILED_INVALID_CREDS';
export const LOGIN_FAILED_SERVER_ERROR = 'LOGIN_FAILED_SERVER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// Registration
export const REGISTERING = 'REGISTERING';
export const REGISTERED = 'REGISTERED';
export const REGISTERING_SUCCESS = 'REGISTERING_SUCCESS';
export const REGISTERING_FAILED = 'REGISTERING_FAILED';
// Set error message
export const SET_ERROR_MSG = 'SET_ERROR_MSG';
export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG';